# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f14d5170d62a800d7085f794bf98e4c0404a68ea42a7144724fcfd77df01ff7e116a38e792fedc495fbeb8945fcec391e7e81d317c0fb4b950471a3c27ed723

test:
  secret_key_base: 1a58c7f9ece5c4f4294931b1843f8a85a4a542f408b02184ba55a40022c68e63cb1f04189a530ebd0b1328c14779693865e54139ebdeff013c79af3331282c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
